"""add_caption_version_history

Revision ID: f75b45c452a2
Revises: 7be3a357459c
Create Date: 2026-02-01 12:21:19.528222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75b45c452a2'
down_revision: Union[str, Sequence[str], None] = '7be3a357459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caption_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('caption_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('operation_description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('vision_model', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caption_id'], ['captions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_caption_versions_caption', 'caption_versions', ['caption_id'], unique=False)
    op.create_index('idx_caption_versions_version', 'caption_versions', ['caption_id', 'version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_caption_versions_version', table_name='caption_versions')
    op.drop_index('idx_caption_versions_caption', table_name='caption_versions')
    op.drop_table('caption_versions')
    # ### end Alembic commands ###
